version: '3.4'

services:
  skygear-server:
    image: quay.io/skygeario/skygear-server:v1.5.0
    depends_on:
      - postgres
    container_name: helloworld_skygear_server
  postgres:
    image: mdillon/postgis:9.5
    container_name: helloworld_postgres
  skygear-plugin:
    image: helloworld/skygear-plugin
    environment:
      SKYGEAR_ADDRESS: tcp://skygear-server:5555
    build:
      context: .
    volumes:
      - ./helloworld:/usr/src/app/helloworld
    depends_on:
      - postgres
    container_name: helloworld_skygear_plugin
